Add a task to list applications and deployments
opus-codium/puppet-application pull request #13
Opened 2022-03-08 23:48 UTC by smortex

This PR also include:
* #12

2022-03-10 20:31 UTC, neomilium requested changes

2022-03-10 20:31 UTC, neomilium commented on tasks/list.rb
> +ApplicationPruneTask.run if $PROGRAM_NAME == __FILE__
`ApplicationListTask` ?

2022-03-10 21:04 UTC, smortex commented on tasks/list.rb
> +ApplicationPruneTask.run if $PROGRAM_NAME == __FILE__
Yes!

2022-03-12 07:26 UTC, neomilium approved these changes

2022-03-12 07:26 UTC, merged